# Generated by Django 6.0.4 on 2026-04-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0002_subject_attendance_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(default="IN", max_length=10),
        ),
        migrations.AlterField(
            model_name="person",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
