# Generated by Django 6.0.4 on 2026-04-18 20:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0003_alter_attendance_status_alter_person_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="recognition.subject",
            ),
        ),
    ]
